apiVersion: apps/v1
kind: Deployment
metadata:
  name: web88
  labels:
    app: web88
spec:
<<<<<<< HEAD
<<<<<<< HEAD
  replicas: 3
=======
  replicas: 2
>>>>>>> 3b3c380 (manifest)
=======
  replicas: 4
>>>>>>> 34b218d (update)
  selector:
    matchLabels:
      app: web88
  template:
    metadata:
      labels:
        app: web88
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

