apiVersion: apps/v1
kind: Deployment
metadata:
  name: web88
  labels:
    app: web88
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web88
  template:
    metadata:
      labels:
        app: web88
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

